#!/usr/bin/env php
<?
declare(strict_types=1);
!defined('ROOT_PATH') && define('ROOT_PATH', __DIR__ . '/');
spl_autoload_register();

	function ff($dir, $call = null) {
		$result = [];
		if (is_dir($dir)) {
			$files = scandir($dir);
			foreach ($files as $file) {
				if ($file == '.' || $file == '..') {continue;}
				$filePath = $dir . DIRECTORY_SEPARATOR . $file;
				if (is_dir($filePath)) {
					$result = array_merge($result, ff($filePath, $call));
				} elseif (is_file($filePath)) {
					if ($call) {$call($filePath, $result);} else { $result[] = $filePath;}
				}
			}
		}
		return $result;
	}



$GLOBALS['tmp'] = "<?\ndeclare (strict_types = 1);\nnamespace{\n!defined('ROOT_PATH') && define('ROOT_PATH', __DIR__ . '/');\nspl_autoload_register();\n";
//加载公共函数
ff(ROOT_PATH.'src',function($e){
	if (str_contains($e,'functions.php')) {
		$t = file_get_contents($e);
		$GLOBALS['tmp'].=str_replace(["<?","declare (strict_types = 1);"], '', $t)."if(PHP_SAPI == 'cli'){lim\Console::run(\$argv);}}";	
	}
});

//加载核心类
$f=ff(ROOT_PATH.'src/core');
foreach ($f as $file) {
	$t = file_get_contents($file);
	$GLOBALS['tmp'].="\nnamespace lim {\n".str_replace(["<?","declare (strict_types = 1);",'namespace lim;'], '', $t)."}\n";
}

file_put_contents(__DIR__.'/out.php', $GLOBALS['tmp']);
